from harness_mcp.catalog import EnvVarSpec, McpServer

BUILTIN_SERVERS: list[McpServer] = [
    McpServer(
        id="github",
        name="GitHub",
        description="Manage repositories, issues, pull requests, and more on GitHub",
        homepage="https://github.com/modelcontextprotocol/servers/tree/main/src/github",
        type="local",
        command=["npx", "-y", "@modelcontextprotocol/server-github"],
        env_vars=[
            EnvVarSpec(
                name="GITHUB_PERSONAL_ACCESS_TOKEN",
                description="GitHub personal access token with repo and issues scopes",
                required=True,
            ),
        ],
        tags=["git", "code-review", "issues", "collaboration"],
    ),
    McpServer(
        id="filesystem",
        name="Filesystem",
        description="Secure file operations with configurable access controls",
        homepage="https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
        type="local",
        command=["npx", "-y", "@modelcontextprotocol/server-filesystem"],
        env_vars=[],
        tags=["files", "system"],
    ),
    McpServer(
        id="playwright",
        name="Playwright",
        description="Browser automation for testing and web scraping",
        homepage="https://github.com/microsoft/playwright-mcp",
        type="local",
        command=["npx", "-y", "@playwright/mcp"],
        env_vars=[],
        tags=["browser", "testing", "web"],
    ),
    McpServer(
        id="brave-search",
        name="Brave Search",
        description="Web search using Brave Search API",
        homepage="https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search",
        type="local",
        command=["npx", "-y", "@modelcontextprotocol/server-brave-search"],
        env_vars=[
            EnvVarSpec(
                name="BRAVE_API_KEY",
                description="Brave Search API key from https://brave.com/search/api/",
                required=True,
            ),
        ],
        tags=["search", "web"],
    ),
    McpServer(
        id="memory",
        name="Memory",
        description="Knowledge graph-based persistent memory system",
        homepage="https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
        type="local",
        command=["npx", "-y", "@modelcontextprotocol/server-memory"],
        env_vars=[],
        tags=["knowledge", "persistence", "memory"],
    ),
    McpServer(
        id="sequential-thinking",
        name="Sequential Thinking",
        description="Dynamic, reflective problem-solving through structured thought sequences",
        homepage="https://github.com/modelcontextprotocol/servers/tree/main/src/sequential-thinking",
        type="local",
        command=["npx", "-y", "@modelcontextprotocol/server-sequential-thinking"],
        env_vars=[],
        tags=["reasoning", "problem-solving"],
    ),
    McpServer(
        id="fetch",
        name="Fetch",
        description="Fetch and convert URLs to markdown for LLM consumption",
        homepage="https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
        type="local",
        command=["npx", "-y", "@modelcontextprotocol/server-fetch"],
        env_vars=[],
        tags=["web", "http", "scraping"],
    ),
    McpServer(
        id="context7",
        name="Context7",
        description="Search through up-to-date library documentation and code examples",
        homepage="https://github.com/upstash/context7",
        type="remote",
        url="https://mcp.context7.com/mcp",
        env_vars=[],
        headers=None,
        tags=["docs", "libraries", "reference"],
    ),
    McpServer(
        id="sentry",
        name="Sentry",
        description="Interact with Sentry for error monitoring and debugging",
        homepage="https://mcp.sentry.dev",
        type="remote",
        url="https://mcp.sentry.dev/mcp",
        env_vars=[],
        tags=["monitoring", "errors", "debugging"],
    ),
    McpServer(
        id="grep",
        name="Grep (Vercel)",
        description="Search through public GitHub code using grep.app",
        homepage="https://grep.app",
        type="remote",
        url="https://mcp.grep.app",
        env_vars=[],
        tags=["code-search", "reference"],
    ),
    McpServer(
        id="serena",
        name="Serena",
        description="Code analysis, symbol lookup, refactoring, and semantic search",
        homepage="https://github.com/oraios/serena",
        type="local",
        command=[
            "uvx",
            "--from",
            "git+https://github.com/oraios/serena",
            "serena",
            "start-mcp-server",
            "--project-from-cwd",
            "--context",
            "agent",
            "--open-web-dashboard",
            "False",
        ],
        env_vars=[],
        tags=["code-analysis", "refactoring", "symbols"],
    ),
    McpServer(
        id="postgres",
        name="PostgreSQL",
        description="Query and explore PostgreSQL databases",
        homepage="https://github.com/modelcontextprotocol/servers/tree/main/src/postgres",
        type="local",
        command=["npx", "-y", "@modelcontextprotocol/server-postgres"],
        env_vars=[
            EnvVarSpec(
                name="DATABASE_URL",
                description="PostgreSQL connection string (e.g. postgresql://user:pass@host/db)",
                required=True,
            ),
        ],
        tags=["database", "sql"],
    ),
    McpServer(
        id="slack",
        name="Slack",
        description="Send and read messages, manage channels on Slack",
        homepage="https://github.com/modelcontextprotocol/servers/tree/main/src/slack",
        type="local",
        command=["npx", "-y", "@modelcontextprotocol/server-slack"],
        env_vars=[
            EnvVarSpec(
                name="SLACK_BOT_TOKEN",
                description="Slack Bot User OAuth token",
                required=True,
            ),
        ],
        tags=["communication", "messaging"],
    ),
    McpServer(
        id="linear",
        name="Linear",
        description="Manage Linear issues, projects, and cycles",
        homepage="https://github.com/linear/linear-mcp",
        type="local",
        command=["npx", "-y", "@linear/mcp"],
        env_vars=[
            EnvVarSpec(
                name="LINEAR_API_KEY",
                description="Linear API key from https://linear.app/settings/api",
                required=True,
            ),
        ],
        tags=["project-management", "issues", "tracking"],
    ),
    McpServer(
        id="docker",
        name="Docker",
        description="Manage Docker containers, images, volumes, and networks",
        homepage="https://github.com/modelcontextprotocol/servers/tree/main/src/docker",
        type="local",
        command=["npx", "-y", "@modelcontextprotocol/server-docker"],
        env_vars=[],
        tags=["containers", "infrastructure", "devops"],
    ),
    McpServer(
        id="puppeteer",
        name="Puppeteer",
        description="Headless Chrome browser automation",
        homepage="https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer",
        type="local",
        command=["npx", "-y", "@modelcontextprotocol/server-puppeteer"],
        env_vars=[],
        tags=["browser", "automation", "testing"],
    ),
    McpServer(
        id="gitlab",
        name="GitLab",
        description="Manage GitLab repositories, merge requests, issues, and CI/CD",
        homepage="https://github.com/modelcontextprotocol/servers/tree/main/src/gitlab",
        type="local",
        command=["npx", "-y", "@modelcontextprotocol/server-gitlab"],
        env_vars=[
            EnvVarSpec(
                name="GITLAB_PERSONAL_ACCESS_TOKEN",
                description="GitLab personal access token with api scope",
                required=True,
            ),
            EnvVarSpec(
                name="GITLAB_API_URL",
                description="GitLab API URL (for self-hosted instances)",
                required=False,
                default="https://gitlab.com/api/v4",
            ),
        ],
        tags=["git", "code-review", "ci-cd", "collaboration"],
    ),
    McpServer(
        id="notion",
        name="Notion",
        description="Interact with Notion pages, databases, and comments",
        homepage="https://github.com/makenotion/notion-mcp-server",
        type="local",
        command=["npx", "-y", "@notionhq/notion-mcp-server"],
        env_vars=[
            EnvVarSpec(
                name="NOTION_API_KEY",
                description="Notion integration token",
                required=True,
            ),
        ],
        tags=["docs", "knowledge", "notes"],
    ),
    McpServer(
        id="serpapi",
        name="SerpAPI",
        description="Google search results via SerpAPI",
        homepage="https://github.com/modelcontextprotocol/servers/tree/main/src/serpapi",
        type="local",
        command=["npx", "-y", "@modelcontextprotocol/server-serpapi"],
        env_vars=[
            EnvVarSpec(
                name="SERPAPI_API_KEY",
                description="SerpAPI key from https://serpapi.com/",
                required=True,
            ),
        ],
        tags=["search", "web", "google"],
    ),
    McpServer(
        id="git",
        name="Git",
        description=(
            "Git operations — status, diff, log, add, commit, push, tag, branch, checkout"
        ),
        homepage="https://github.com/modelcontextprotocol/servers/tree/main/src/git",
        type="local",
        command=["uvx", "mcp-server-git"],
        env_vars=[],
        tags=["git", "version-control", "vcs"],
    ),
]
